### ISSUE TITLE
strength point

### ISSUE THREAD

**Issue by ghost** [palaster/Get-A-Job#2]
i gave just 1 strength and i hit 150 dmg with a wooden sword........ please fix this... forge 2282

**Comment by palaster** [comment]
I fixed this issue on the 1.10.2, but forgot to put it in 1.11.2 version. Update to the new 1.11.2 version.

**Comment by ghost** [comment]
i installed latest update, still hitting 100 dmg...

**Comment by ghost** [comment]
should i create new world? or it isn't fixed

**Comment by palaster** [comment]
No, it is fixed, but you would have to a) kill yourself (to reset strength), b) level-up the strength skill, or c) to create a new world. I would suggest doing it in that order, but I suspect the changes I made might require a new world. OR, if you're advance deleting your player.dat file might fix it as well.
